/*
Copyright 2026 Chainguard, Inc.
SPDX-License-Identifier: Apache-2.0
*/

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"text/template"

	"chainguard.dev/driftlessaf/agents/metaagent"
	"chainguard.dev/driftlessaf/agents/toolcall/callbacks"
	"chainguard.dev/driftlessaf/reconcilers/githubreconciler/changemanager"
	"chainguard.dev/driftlessaf/reconcilers/githubreconciler/clonemanager"
	"chainguard.dev/driftlessaf/reconcilers/githubreconciler/metapathreconciler"
	gogit "github.com/go-git/go-git/v5"
)

const (
	prTitleTemplate = `fix(modernize): apply modernize fixes to {{.Path}}`
	prBodyTemplate  = `Automated Go modernize fixes applied by {{.Identity}}.

---
*Generated by {{.Identity}}*`
)

// reconciler is a type alias for the composed metapathreconciler.
type reconciler[CB any] = metapathreconciler.Reconciler[*Request, *Result, CB]

// newReconciler constructs a reconciler from configuration.
func newReconciler[CB any](
	ctx context.Context,
	identity string,
	agent metaagent.Agent[*Request, *Result, CB],
	cloneMeta *clonemanager.Meta,
	prLabels []string,
	buildCallbacks func(*gogit.Worktree, *changemanager.Session[metapathreconciler.PRData]) CB,
) (*reconciler[CB], error) {
	identity = strings.TrimSpace(identity)
	if identity == "" {
		return nil, errors.New("identity must be provided")
	}
	if agent == nil {
		return nil, errors.New("agent must be provided")
	}
	if cloneMeta == nil {
		return nil, errors.New("cloneMeta must be provided")
	}

	titleTmpl, err := template.New("title").Parse(prTitleTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse title template: %w", err)
	}
	bodyTmpl, err := template.New("body").Parse(prBodyTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse body template: %w", err)
	}

	cm, err := changemanager.New[metapathreconciler.PRData](identity, titleTmpl, bodyTmpl,
		changemanager.WithFindingsIteration[metapathreconciler.PRData](),
	)
	if err != nil {
		return nil, fmt.Errorf("create change manager: %w", err)
	}

	return metapathreconciler.New(ctx, identity, &goModernize{}, cm, cloneMeta, prLabels, agent,
		func(findings []callbacks.Finding) *Request {
			return &Request{Findings: findings}
		},
		buildCallbacks,
	)
}
